POST http://localhost:3031/api/notes
Content-Type: application/json

{
    "content" :"Vs code rest client is pretty handy tool",
    "important":true
}

#  add multiple requests in the same file using ### separators: